# Generated by Django 4.2.4 on 2023-09-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=80)),
                ('skillIcon', models.ImageField(upload_to='static/img/skills')),
                ('progress', models.IntegerField()),
            ],
        ),
    ]
