# Generated by Django 4.2.4 on 2023-09-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('fend', models.CharField(max_length=300, null=True)),
                ('bend', models.CharField(max_length=300, null=True)),
                ('db', models.CharField(max_length=300, null=True)),
                ('pl', models.CharField(max_length=300, null=True)),
                ('tools', models.CharField(max_length=300, null=True)),
                ('software', models.CharField(max_length=300)),
            ],
        ),
    ]
