# Generated by Django 4.2.4 on 2023-09-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feature',
            field=models.ImageField(default=1, upload_to='static/img/projects'),
            preserve_default=False,
        ),
    ]
