# Generated by Django 4.2.4 on 2023-09-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
