# Generated by Django 4.2.4 on 2023-09-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='des',
            new_name='content',
        ),
        migrations.AddField(
            model_name='project',
            name='shortDes',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
