# Generated by Django 4.2.4 on 2023-09-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_des_project_content_project_shortdes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='live',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
